# Generated by Django 3.1.6 on 2021-06-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('time_during_the_day', models.TimeField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'bot_message',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('alive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bot_subscriber',
            },
        ),
        migrations.CreateModel(
            name='SubscriberMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymbot.botmessage')),
                ('subscriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymbot.subscriber')),
            ],
            options={
                'db_table': 'subscriber_message',
                'unique_together': {('subscriber', 'message')},
            },
        ),
    ]
