# Generated by Django 3.1.6 on 2021-06-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_message_id', models.BigIntegerField()),
                ('answered', models.BooleanField(default=False)),
                ('answer_message_id', models.BigIntegerField()),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymbot.botmessage')),
            ],
        ),
    ]
