# Generated by Django 3.1.6 on 2021-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbot', '0003_auto_20210601_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='for_user_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='messagehistory',
            unique_together={('for_user_id', 'tg_message_id')},
        ),
    ]
