# Generated by Django 3.1.6 on 2021-06-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymbot', '0004_auto_20210601_1704'),
    ]

    operations = [
    ]
