# Generated by Django 3.1.6 on 2021-06-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymbot', '0005_auto_20210601_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnswerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('for_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymbot.botmessage')),
            ],
        ),
    ]
