# Generated by Django 3.1.6 on 2021-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbot', '0006_botanswermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
